export const CATEGORIES_EN_TO_ES = {
  "Air Filters": "Filtros de Aire",
  "Air Intake Systems": "Sistemas de Admisión",
  "Apparel": "Indumentaria",
  "Bags & Packs": "Bolsos y Mochilas",
  "Batteries, Starting & Charging": "Baterías, Arranque y Carga",
  "Body Armor & Protection": "Protección de chasis",
  "Brakes, Rotors & Pads": "Frenos, Discos y Pastillas",
  "Cooling": "Refrigeración",
  "Data Acquisition": "Adquisición de Datos",
  "Drivetrain": "Transmisión",
  "Engine Components": "Motor",
  "Exhaust, Mufflers & Tips": "Escape y Silenciadores",
  "Exterior Styling": "Estilo Exterior",
  "Fabrication": "Fabricación",
  "Floor Mats": "Pisos",
  "Forced Induction": "Inducción Forzada",
  "Fuel Delivery": "Combustible",
  "Gauges & Pods": "Indicadores y Pods",
  "Ignition": "Encendido",
  "Interior Accessories": "Accesorios Interiores",
  "Lights": "Luces",
  "Marketing": "Marketing",
  "Oils & Oil Filters": "Aceites y Filtros de Aceite",
  "Programmers & Chips": "Programadores y Chips",
  "Roofs & Roof Accessories": "Techos y Accesorios de Techo",
  "Safety": "Seguridad",
  "Seats": "Asientos",
  "Suspension": "Suspensión",
  "Tools": "Herramientas",
  "Truck Bed Accessories": "Accesorios para Caja de Camioneta",
  "Uncategorized": "Sin Categorizar",
  "Wheel and Tire Accessories": "Accesorios de Llantas y Cubiertas",
  "Wheels": "Llantas",
  "Winches & Hitches": "Lingas y Enganches",
  "Windshields": "Parabrisas",
} as const;

export type CategoryES = (typeof CATEGORIES_EN_TO_ES)[keyof typeof CATEGORIES_EN_TO_ES];
